PR - Enumerable Methods
nurislam-ab/enumerable-methods pull request #2
Opened 2020-03-05 14:46 UTC by nurislam-ab

This PR contains enumerable methods including:
- my_each
- my_each_with_index
- my_select
- my_all?
- my_any?
- my_none?
- my_count
- my_map
- my_inject

Also there is an additional method called multiply_els for testing purposes of the my_inject method

2020-03-05 19:57 UTC, mosesogwo requested changes
**HI @nurislam-ab, good work:clap:. Now consider the following:**

1. my_each_with_index should call the given block once for each element in the enum. For example:
       `[5, 6, 7].my_each_with_index { |ele, idx| p "#{ele} is at index #{idx}" }`
 should print out 
`"5 is at index 0"`
`"6 is at index 1"`
`"7 is at index 2"`

2. my_all? should return true when no block is given and none of the elements is nil or false.

3. my_all? should return true when a class is passed as an argument and all of the elements in the enum are members of such class
e.g `[1, 2, 3].my_all?(Integer) => true`

4. my_all? should return true when a Regex is passed as an argument and all of the elements in the enum matches the Regex.
e.g. `['cook', 'book'].my_all?(/([a-z])ook/) => true`

5.  my_all? should return true when a pattern other than Regex or a Class is given and all of the elements of the enum matches the pattern
e.g. `['ook', 'ook'].my_all?('ook') => true`

6. my_any? should return true when no block or argument is given and there is at least one element in the enumerable that is not false or nil.

7. my_any? should return true when a class is passed as an argument and there is at least one element in the enumerable that belongs to that class.

8. When a regex is passed as an argument to my_any? and none of the members of the enumerable matches the regex, it should return false.

9. When a pattern other than a regex or class is passed as an argument to my_any? and none of the members of the enumerable matches the pattern, my_any should return false.

9. When no argument or block is given to my_none?, it should return true only if no member of the enumerable is true.
e.g `[1, 2, 3].my_none?` should return `false`
       `[false, nil].my_none?` should return `true`

10.  When a class is passed as an argument to my_none?, it should return true only if none of the collection is a member of the given class.

11. When a regex is passed as an argument to my_none?, it should return true only if none of the collection matches the given regex.

12. When a pattern other than a regex or class is passed as an argument to my_none?, it should return true only if none of the collection matches the given pattern.

13. If an argument is given to my_count, it should return the number of elements in the enum that are equal to the given argument. You should consider situations where an argument is passed in your my_count method.
`[1, 2, 2, 3].my_count(2)` should return 2.

14. Consider the case when a block is passed to my_count. It should return the number of elements in the enum for which the block yields true.

15. When my_map is given a block, it should return an array with the results of running the block once for each element in the enum.
`(1..4).my_map { |i| i*i }`  should return `[1, 4, 9, 16]`, not `16`

16.Look at this [resource](https://ruby-doc.org/core-2.7.0/Enumerable.html#method-i-inject) for the inject method and adjust your my_inject method accordingly.

- Do we need a package-lock.json file in this project? If not, please remove the file.

_**Kindly ensure that your methods handle the above scenarios and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

2020-03-17 22:14 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @nurislam-ab :handshake: 

### Thank you for doing the changes requested by the previous reviewer, some of your enumerable methods still some work to do :construction: :construction_worker_man: so please address to the comments I've made in your code :point_down: 

### That's it! :raised_hands: 

### Please :pray: do the changes :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any questions? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-03-17 22:14 UTC, euqueme commented on enum.rb
> +  end
#### my_all? 

- [x] when no block or argument is given returns true only when none of the collection members are false or nil if the mentioned condition is not met it should return false

     > this [nil, false, true, []].my_all? should be equal to this [nil, false, true, []].all? => false

- Yours is retrieving a NameError
![image](https://user-images.githubusercontent.com/52209067/76903545-d69ebe00-6863-11ea-9c99-592dc7423fc8.png)

- Real
![image](https://user-images.githubusercontent.com/52209067/76903589-eb7b5180-6863-11ea-878c-fe92864fc1a1.png)

- [x] when a class is passed as an argument returns true only if all of the collection is a member of such class, otherwise, it should return false

     > [1, 2.5, 'a', 9].my_all?(Integer) should be equal to this [1, 2.5, 'a', 9].all?(Integer) => false

- Yours is giving an ArgumentError
![image](https://user-images.githubusercontent.com/52209067/76903677-136ab500-6864-11ea-9d46-426ca3984f57.png)

- Real
![image](https://user-images.githubusercontent.com/52209067/76903728-267d8500-6864-11ea-9170-df44cdea1d85.png)

- [x] when a Regex is passed as an argument returns true if all of the collection matches the Regex

     >  %w[dog door rod blade].my_all?(/d/) should be equal to this %w[dog door rod blade].all?(/d/) => true

- Yours is retrieving an ArgumentError
![image](https://user-images.githubusercontent.com/52209067/76904239-36e22f80-6865-11ea-9611-19f626ae456f.png)

- Real
![image](https://user-images.githubusercontent.com/52209067/76904287-4a8d9600-6865-11ea-83a9-42a1a8954ea4.png)

- [x] when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern

     > [3,4,7,11].my_all?(3) should be equal to this [3,4,7,11].all?(3)  => false 

- Yours is retrieving an ArgumentError
![image](https://user-images.githubusercontent.com/52209067/76904381-790b7100-6865-11ea-8c29-f821539ed449.png)

- Real
![image](https://user-images.githubusercontent.com/52209067/76904421-8aed1400-6865-11ea-92a5-5b9693f77d63.png)

2020-03-17 22:14 UTC, euqueme commented on enum.rb
> +  end
#### my_any?

- [x] when a class is passed as an argument returns true if at least one of the collection is a member of such class

     > this [1, 2.5, 'a', 9].my_any?(Integer) should be equal to this [1, 2.5, 'a', 9].any?(Integer) => true

- Yours is retrieving the wrong result
![image](https://user-images.githubusercontent.com/52209067/76905405-7d388e00-6867-11ea-84db-226ed0516ea7.png)

- Real
![image](https://user-images.githubusercontent.com/52209067/76905420-87f32300-6867-11ea-96f4-b2aefeebbcc2.png)

- [x] when a Regex is passed as an argument returns false if none of the collection matches the Regex

     > %w[dog door rod blade].my_any?(/o/) should be equal to this %w[dog door rod blade].any?(/o/) => true

- Yours is retrieving the wrong result
![image](https://user-images.githubusercontent.com/52209067/76905538-c1c42980-6867-11ea-942f-c29dab72192a.png)

- Real
![image](https://user-images.githubusercontent.com/52209067/76905560-cdafeb80-6867-11ea-8180-d5e5aa449715.png)

2020-03-17 22:14 UTC, euqueme commented on enum.rb
> +  end
#### my_none?

- [ ] when a class is passed as an argument returns true if none of the collection is a member of such class

     > this [1, 2.5, 'a', 9].my_none?(Integer) should be equal to this [1, 2.5, 'a', 9].none?(Integer) => false

- Yours is giving the wrong answer
![image](https://user-images.githubusercontent.com/52209067/76905797-4c0c8d80-6868-11ea-9f3a-f4bbe4fbdfb8.png)

- Real
![image](https://user-images.githubusercontent.com/52209067/76905820-59297c80-6868-11ea-992c-3264fd368649.png)

- [ ] when a Regex is passed as an argument returns true only if none of the collection matches the Regex

     > %w[dog door rod blade].my_none?(/o/) should be equal to this %w[dog door rod blade].none?(/o/) => false

- Yours is retrieving the wrong answer
![image](https://user-images.githubusercontent.com/52209067/76905915-8e35cf00-6868-11ea-9a23-085357c387ac.png)

- Real
![image](https://user-images.githubusercontent.com/52209067/76905954-9db51800-6868-11ea-8b05-bb9675e2ff16.png)

2020-03-17 22:14 UTC, euqueme commented on enum.rb
> +  end
#### my_map

- [ ] accepts a proc as an argument and returns a new array with the results of running the proc once for every element in enum.

Given 
`my_proc = Proc.new {|num| num > 10 }`

- Yours is giving the wrong answer
![image](https://user-images.githubusercontent.com/52209067/76906403-7d398d80-6869-11ea-8d77-e97eed83ee47.png)

- Real
![image](https://user-images.githubusercontent.com/52209067/76906442-8cb8d680-6869-11ea-9f6d-d864f9cef00b.png)

[OPTIONAL]

- [ ] in the specifications of the project in the [Odin project](https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-building-blocks) # 12, you were asked to modify your my_map method to take either a proc or a block. And if both a proc and a block are given, only execute the proc. The real map doesn't have this feature, but you were asked to have it so I strongly recommend making it work

Given 
`my_proc = Proc.new {|num| num > 10 }`

Result
> puts [18, 22, 5, 6] .my_map(my_proc) {|num| num < 10 }  # true true false false

2020-03-22 06:53 UTC, suretrust approved these changes
Hi @nurislam-ab, 👋 

### Great job implementing the suggested changes. 🙌 No deal-breaker, let's get this merged! 👍 

_Good luck with your future projects and happy coding!_ 🎉

2020-03-22 06:53 UTC, suretrust commented on enum.rb
> +class Enumerable
This should be `module Enumerable`, not a class.

2020-03-22 07:14 UTC, merged